### ISSUE TITLE
T00 usage in AMPS 

### ISSUE THREAD

**Issue by yzhan-met** [alcf-lidar/alcf#1]
Hi there, I'm Yizhe from MetService. While I'm testing ALCF using our WRF data, I found the usage of T00 to calculate `theta` may be incorrect according to the WRF developer (screenshot attached).
![Picture1](https://user-images.githubusercontent.com/57605888/233485171-c8b0a108-1bb1-4e7b-9c69-304eef893b5a.png)

Since `T00` is much less than 300, it may impact on the follow-up simulation (e.g., simulated backscattering coeff., cloud detection).

**Comment by peterkuma** [comment]
Hi Yizhe,

Thank you for notifying me about this issue. I wrongly assumed that the description of T in the input files (`perturbation potential temperature (theta-t0)`) means that T00 is the base temperature. It is now fixed in the master branch and I will aim to release a new version soon.

**Comment by yzhan-met** [comment]
Hi Peter, glad to see it gets resolved so quickly.

Thanks,
Yizhe
________________________________

**Comment by peterkuma** [comment]
This is now fixed in v1.4.1.
